### ISSUE TITLE
Samurai Jack

### ISSUE THREAD

**Issue by papiness77** [ValSpada/parcialesFuncional#1]
-- a.
esMalvado :: Personaje -> Bool
esMalvado (UnPersonaje _ unosElementos _) = any (== "Maldad") . map tipo $ unosElementos

EL map es inneceario, estas abriendo la lista dos veces cuando podrias hacerlo solo una vez

any ( (=="Maldad") . tipo)

**Comment by ValSpada** [comment]
Tenes razón, muchas gracias por decirme ! <3

**Comment by julian-berbel** [comment]
Alternativamente `elem "Maldad" . map tipo` también sería una opción válida.
