### ISSUE TITLE
Correcciones - Transformers

### ISSUE THREAD

**Issue by julian-berbel** [ValSpada/parcialesFuncional#5]
https://github.com/ValSpada/parcialesFuncional/blob/2d4a239db3581a12484650315a178079b5f709b9/transformers.hs#L85-L86

Repite código. Si queremos ver si una condición se cumple para varios valores podemos usar `all` y una lista. (Y ahí entra la función uncurry del tip)
```haskell
--                                  vvvvvvvvvvvvvvvvvvvv definiéndola de esta forma, leDominaComo puede tomar los dos autobots por separado en vez de como una tupla
domina unAutobot otroAutobot = all (uncurry leDominaComo) combinacionesPosibles
  where combinacionesPosibles = [(unAutobot, otroAutobot), (unAutobot, transformar otroAutobot), (transformar unAutobot, otroAutobot), (transformar unAutobot, transformar otroAutobot)]
```

https://github.com/ValSpada/parcialesFuncional/blob/2d4a239db3581a12484650315a178079b5f709b9/transformers.hs#L92-L94

Poco declarativo. Usar `all`.

https://github.com/ValSpada/parcialesFuncional/blob/2d4a239db3581a12484650315a178079b5f709b9/transformers.hs#L99-L100

Ojo con el enunciado; pide devolver **los nombres** de los autobots que cumplen con la condición. No los autobots en sí.

**Comment by ValSpada** [comment]
Correcciones hechas
